// Production end-to-end smoke test — hits the real /api/send-quote on Vercel.
// Builds a minimal labelled PDF, posts it to the prod API, prints the full response.
// Side effects in PROD: 1 Drive file, 1 email to the devis inbox, 1 DB row.
// Filename / clientName are clearly marked as a smoke test so cleanup is trivial.
import { jsPDF } from 'jspdf';

const PROD = process.env.PROD_URL || 'https://generateur-devis.vercel.app';

const doc = new jsPDF('portrait', 'pt', 'a4');
doc.setFontSize(14);
doc.text('SMOKE TEST — handoff verification', 40, 60);
doc.setFontSize(10);
doc.text(new Date().toISOString(), 40, 80);
doc.text('Auto-generated by scripts/smoke-prod.mjs', 40, 100);
const blob = doc.output('blob');
const buf = Buffer.from(await blob.arrayBuffer());
const base64 = buf.toString('base64');

const filename = `smoke-test-${new Date().toISOString().replace(/[:.]/g, '-')}.pdf`;
console.log('POST', PROD + '/api/send-quote');
console.log('  filename:', filename);
console.log('  pdf size:', buf.length, 'bytes (', base64.length, 'b64)');

const started = Date.now();
const resp = await fetch(`${PROD}/api/send-quote`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    pdfBase64: base64,
    filename,
    commercial: 'Arnaud Bloch',
    clientName: 'Smoke Test (auto)',
    type: 'alarme',
    produits: [],
    addCommercialOverlay: false,
    mergedByFrontend: true,
    timestamp: new Date().toISOString(),
  }),
});
const elapsed = ((Date.now() - started) / 1000).toFixed(1);

console.log('HTTP', resp.status, resp.statusText, `(${elapsed}s)`);
const text = await resp.text();
let parsed;
try { parsed = JSON.parse(text); } catch { parsed = text; }
console.log('Response:');
console.log(JSON.stringify(parsed, null, 2));
